### ISSUE TITLE
Release date of new version with firewall?

### ISSUE THREAD

**Issue by minutephp** [malc0mn/vultr-api-client#1]
Just discovered this library and I must say this is just excellent. The way it is organized is just intuitive and doesn't require you to look up documentation. I wish AWS SDK was this easy but I guess they just have too many calls to cover. Sorry I digress.

Anyway, i was wondering when the new version with Firewall will be released? I'm currently using the dev branch in my project, but would rather switch to a stable release soon.

Thanks again for the excellent work!

**Comment by malc0mn** [comment]
Thanks for your feedback! Normally sometime next week a new release will be available...

**Comment by malc0mn** [comment]
Hmmm, I now notice I never updated this issue, the [1.1.0](https://github.com/malc0mn/vultr-api-client/tree/1.1.0) release was added on Tue Mar 14 09:17:47 2017 +0100
