### ISSUE TITLE
How create an ISO from a URL?

### ISSUE THREAD

**Issue by pepo-ec** [malc0mn/vultr-api-client#2]
Hi friend, I'm using the project to handle my Vultr account and it's going pretty well, however, how could I create an ISO image from a URL? That is, how can I use the "/v1/iso/create_from_url" API?

**Comment by malc0mn** [comment]
Hmmm... Incredible that I missed that API call!

It's not implemented in this client so I'm going to add it ASAP and will let you know when it's ready!

**Comment by malc0mn** [comment]
Added support for this call. If you could confirm it works, I'll add a new release tag...

**Edit**
Oh, to use it just use these calls:
```php
<?php
$client = new VultrClient(
    new GuzzleHttpAdapter('your-api-key')
);

$client->iso()->getList();
$client->iso()->createFromUrl(
    'http://example.com/path/to/CentOS-6.5-x86_64-minimal.iso'
);

?>
```

So the getIsoList() method on the MetaData() class has been moved ;-)

**Comment by pepo-ec** [comment]
This looks amazing and works great.
